#!perl

use strict;
use warnings;
use OreZen::Util;
use OreZen::Flavor;
use Data::Section::Simple qw(get_data_section);
use Getopt::Compact::WithCmd;

my $go = Getopt::Compact::WithCmd->new(
    args          => 'project',
    global_struct => {
        flavor => {
            alias => [qw/f/],
            type  => '=s',
            desc  => 'sets Flavor',
            opts  => { default => 'Default' },
        },
    },
);

my $opts    = $go->opts || $go->show_usage;
my $project = shift     || $go->show_usage;
mkdir $project or die "$!: $project";
chdir $project or die "$!: $project";

my $flavor = OreZen::Flavor->load($opts->{flavor});
$flavor->gen();

my $data = get_data_section();
for my $path (keys %$data) {
    OreZen::Util->try_mkpath($path);
    OreZen::Util->write($path, $data->{$path});

    if ($path =~ /.pl$/) {
        chmod 0755, $path or warn "$!: $path";
    }
}

print "done\n";

__DATA__
@@ build.pl
#!/usr/bin/env perl

use strict;
use warnings;
use OreZen;
use OreZen::Util;
use OreZen::Flavor;
use Text::MicroTemplate qw(encoded_string);
use Text::MicroTemplate::File;
use Getopt::Compact::WithCmd;

my $go = Getopt::Compact::WithCmd->new(
    args          => 'orezen.txt',
    global_struct => {
        regen => {
            alias => [qw/r/],
            type  => '!',
            desc  => 'regenerate Flavors',
        },
        flavor => {
            alias => [qw/f/],
            type  => '=s',
            desc  => 'sets Flavor',
            opts  => { default => 'Default' },
        },
    }
);

my $opts = $go->opts;
my $file = shift || 'orezen.txt';

my $title;
my $data = do {
    open my $fh, '<', $file or die "$file: $!";
    $title = <$fh>;
    $title ||= '';
    chomp($title);
    local $/;
    <$fh>;
};
my $content = OreZen->format($data);

my $html = Text::MicroTemplate::File->new(
    include_path => 'tmpl',
)->render_file('index.mt', $title, encoded_string $content);

if ($opts->{regen}) {
    my $flavor = OreZen::Flavor->load($opts->{flavor});
    print "regen from $flavor\n";
    $flavor->gen();
}

OreZen::Util->write('index.html', $html);

print "done.\n";
@@ orezen.txt
orezen

>>>
@@@@
<div style="text-align: center">
@@@@
= How to %%red:orezen%% syntax =
@@@@
</div>
@@@@

- section
- header
- code
- link
- list
- table
- hr
- del
- strong
- em
- code
- color
- comment section
- free space

<<<

>>>
= section =

{{{
>>>
...
<<<
}}}

<<<

>>>
= header =

{{{
= h1 =
== h2 ==
=== h3 ===
}}}

= h1 =
== h2 ==
=== h3 ===

<<<

>>>
= code =

@@@@
<pre>
{{{
write here any code
}}}
</pre>
@@@@

<<<

>>>
= link =

bare link

{{{
http://example.com/
}}}

http://example.com/

----

namaed link

{{{
[http://example.com/ example.com]
}}}

[http://example.com/ example.com]


----

image link

{{{
[i:image/foo.jpg]
}}}

[i:image/OP2.jpg]

<<<

>>>
= list =

== standard ==

{{{
- foo
- bar
 - baz

1. hoge
1. fuga
1. piyo
}}}

- foo
- bar
 - baz

1. hoge
1. fuga
1. piyo

----

== mixed ==

{{{
- foo
 - bar
  1. baz
   1. hoge
 - fuga
- piyo
}}}

- foo
 - bar
  1. baz
   1. hoge
 - fuga
- piyo

<<<

>>>
= table =

{{{
| *foo | *bar | *baz |
| hoge | fuga | piyo |
}}}

| *foo | *bar | *baz |
| hoge | fuga | piyo |

<<<

>>>
= hr =

{{{
----
}}}

----

<<<

>>>
= del =

{{{
~~delete here~~
}}}

~~delete here~~

<<<

>>>
= strong =

{{{
''strong word''
}}}

''strong word''

<<<

>>>
= em =

{{{
//em word//
}}}

//em word//

<<<

>>>
= code =

{{{
{{code}}
}}}

{{code}}

<<<

>>>
= color =

{{{
here is %%red:red%%
}}}

here is %%red:red%%

<<<

>>>
= free space =

{{{
@@@@
<p>here is <strong>free</strong> space!</p>
@@@@
}}}

@@@@
<p>here is <strong>free</strong> space!</p>
@@@@

<<<

>>>
= comment section =

{{{
####
here is comment section!
####
}}}

####
here is comment section!
####

<<<

>>>

@@@@
<div style="text-align: center; font-size: 200%">
fin.
</div>
@@@@

<<<
